# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 413)
        MainWindow.setStyleSheet("QMainWindow {\n"
"\n"
"background: #1284FD;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 391, 31))
        self.comboBox.setObjectName("comboBox")
        self.imageCover = QtWidgets.QLabel(self.centralwidget)
        self.imageCover.setGeometry(QtCore.QRect(520, 70, 261, 281))
        self.imageCover.setStyleSheet("QLabel {\n"
"\n"
"background: #7D8C9C;\n"
"border-radius: 10px;\n"
"}")
        self.imageCover.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.imageCover.setText("")
        self.imageCover.setAlignment(QtCore.Qt.AlignCenter)
        self.imageCover.setObjectName("imageCover")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 10, 93, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: #fff;\n"
"    font: 8pt \"Tahoma\";\n"
"background: #59A7FE;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"QPushButton::hover{\n"
"background: #1472DA;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 491, 281))
        self.tableWidget.setStyleSheet("QHeaderView {\n"
"background-color: #EEFFFF;\n"
"font-size:13px;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"color: #fff;\n"
"border-style: solid;\n"
"border-radius: 4px;\n"
"background-color: qlineargradient( x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #4287ff, stop: 1 #356ccc);\n"
"}\n"
"QTableView {\n"
"border: 2px solid #3873d9;\n"
"border-top-color: #4287ff;\n"
"border-radius: 10px;\n"
"background-color: #EEFFFF;\n"
"gridline-color: #777;\n"
"selection-background-color: #ccdfff;\n"
"color:#333;\n"
"font-size:14px;\n"
"font-weight: bold;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 798, 26))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "OPEN LIST"))
